# Generated by Django 4.2.1 on 2023-07-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffprofile_address_remove_staffprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='joinDate',
        ),
    ]
