# Generated by Django 4.2.1 on 2023-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staffprofile_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='joinDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
