# Generated by Django 4.2.1 on 2023-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='shift',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
