# Generated by Django 4.2.1 on 2023-07-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('cart', '0004_historycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.voucher'),
        ),
    ]
