# Generated by Django 4.2.1 on 2023-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_paid'),
        ('cart', '0005_cart_voucher'),
    ]

    operations = [
    ]
