# Generated by Django 4.1.9 on 2023-07-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coupon'),
        ('cart', '0005_alter_cart_item_phone_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item_phone',
            name='hard',
        ),
        migrations.AddField(
            model_name='cart_item_phone',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram'),
        ),
        migrations.AddField(
            model_name='cart_item_phone',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage'),
        ),
    ]
