# Generated by Django 4.2.1 on 2023-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_merge_0005_cart_paid_0005_cart_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
