# Generated by Django 4.1.9 on 2023-07-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_storage_tabletoptionhard_storage'),
        ('cart', '0006_remove_cart_item_phone_hard_cart_item_phone_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item_phone',
            name='price_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.phoneoptionhard'),
        ),
    ]
