# Generated by Django 4.1.9 on 2023-07-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_item_phone_price_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item_phone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='cart_item_phone',
            name='storage',
        ),
    ]
