# Generated by Django 4.1.9 on 2023-07-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_storage_tabletoptionhard_storage'),
        ('cart', '0008_remove_cart_item_phone_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_item_tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tabletoptioncolor')),
                ('price_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tabletoptionhard')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tablet')),
            ],
        ),
    ]
