# Generated by Django 4.2.1 on 2023-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_admin_profile_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
