# Generated by Django 4.1.9 on 2023-06-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackPhoneCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPhoneCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopBattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopOS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopScreen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSpecial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopUSB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopVGA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneChips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneScreen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletBackCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletBattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletChip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletConnect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletFrontCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletOS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletScreen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabletStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchBoMay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchChatLieu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchChongNuoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchDiameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watchQuocGia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('DoiTuong', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('UniSex', 'Unisex')], max_length=10)),
                ('Info', models.TextField()),
                ('BoMay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchbomay')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchbrand')),
                ('ChatLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchchatlieu')),
                ('ChongNuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchchongnuoc')),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchday')),
                ('DuongKinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchdiameter')),
                ('QuocGia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchquocgia')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('Info', models.TextField()),
                ('BackCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbackcamera')),
                ('Connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletconnect')),
                ('FrontCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletfrontcamera')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletos')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbattery')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbrand')),
                ('chips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletchip')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletcolor')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletscreen')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletstorage')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producttype'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('Info', models.TextField()),
                ('BackCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.backphonecamera')),
                ('FrontCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.frontphonecamera')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phoneos')),
                ('Sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonesim')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonebattery')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonebrand')),
                ('chips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonechips')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonecolor')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonescreen')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
                ('Info', models.TextField()),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopcpu')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopos')),
                ('Special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopspecial')),
                ('USB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopusb')),
                ('VGA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopvga')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopbrand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopcolor')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopdesign')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopscreen')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopsize')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopstorage')),
            ],
        ),
    ]
