# Generated by Django 4.2.1 on 2023-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.IntegerField(default=0, null=True)),
                ('tablet', models.IntegerField(default=0, null=True)),
                ('phone', models.IntegerField(default=0, null=True)),
                ('watch', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
    ]
