# Generated by Django 4.1.9 on 2023-06-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_remove_discount_product_id_remove_laptop_cpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('DoiTuong', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('UniSex', 'Unisex')], max_length=10)),
                ('Info', models.TextField()),
                ('BoMay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchbomay')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchbrand')),
                ('ChatLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchchatlieu')),
                ('ChongNuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchchongnuoc')),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchday')),
                ('DuongKinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchdiameter')),
                ('QuocGia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.watchquocgia')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('Info', models.TextField()),
                ('BackCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbackcamera')),
                ('Connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletconnect')),
                ('FrontCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletfrontcamera')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletos')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbattery')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletbrand')),
                ('chips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletchip')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletcolor')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletscreen')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletstorage')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('Info', models.TextField()),
                ('BackCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.backphonecamera')),
                ('FrontCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.frontphonecamera')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phoneos')),
                ('Sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonesim')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonebattery')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonebrand')),
                ('chips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonechips')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonecolor')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonescreen')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image0', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
                ('Info', models.TextField()),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopcpu')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopos')),
                ('Special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopspecial')),
                ('USB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopusb')),
                ('VGA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopvga')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopbrand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopcolor')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopdesign')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopram')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopscreen')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopsize')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.laptopstorage')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
