# Generated by Django 4.2.1 on 2023-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
