# Generated by Django 4.1.9 on 2023-06-25 09:00

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_product_delete_tablet_delete_watch'),
        ('home', '0002_alter_laptop_image0_alter_laptop_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_id', models.IntegerField(verbose_name=home.models.Phone)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopcolor')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopstorage')),
            ],
        ),
    ]
