# Generated by Django 4.1.9 on 2023-07-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('home', '0002_voucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='BackCamera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.backphonecamera'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='FrontCamera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.frontphonecamera'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='OS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneos'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonesim'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonebattery'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonebrand'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='chips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonechips'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonecolor'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonescreen'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
