# Generated by Django 4.1.9 on 2023-06-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_phoneoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneoption',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneoption',
            name='Phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone'),
        ),
    ]
