# Generated by Django 4.1.9 on 2023-07-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_phone_backcamera_alter_phone_frontcamera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoptionhard',
            name='Phone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.phone'),
        ),
    ]
