# Generated by Django 4.1.9 on 2023-07-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('home', '0004_alter_phoneoptionhard_phone_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='CPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopcpu'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='OS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopos'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='USB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopusb'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='VGA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopvga'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopbrand'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopcolor'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopdesign'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopram'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopscreen'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopsize'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.laptopstorage'),
        ),
        migrations.AlterField(
            model_name='phoneoptionhard',
            name='Phone_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.phone'),
        ),
        migrations.AlterField(
            model_name='tabletoptionhard',
            name='Tablet_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tablet'),
        ),
    ]
