# Generated by Django 4.1.9 on 2023-06-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_product_delete_tablet_delete_watch'),
        ('home', '0004_phoneoption_price_alter_phoneoption_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoption',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonecolor'),
        ),
        migrations.AlterField(
            model_name='phoneoption',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage'),
        ),
    ]
