# Generated by Django 4.1.9 on 2023-07-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('home', '0006_alter_tablet_info_alter_tablet_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoptioncolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonecolor'),
        ),
        migrations.AlterField(
            model_name='tabletoptioncolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tabletcolor'),
        ),
    ]
