# Generated by Django 4.2.1 on 2023-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tablet_backcamera_alter_tablet_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_product',
            field=models.IntegerField(null=True),
        ),
    ]
