# Generated by Django 4.1.9 on 2023-06-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_product_delete_tablet_delete_watch'),
        ('home', '0008_tabletoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOptionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('Phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOptionRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_add', models.IntegerField(blank=True, null=True)),
                ('Phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOptionStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_add', models.IntegerField(blank=True, null=True)),
                ('Phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
            ],
        ),
        migrations.CreateModel(
            name='TabletOptionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('Tablet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tablet')),
            ],
        ),
        migrations.CreateModel(
            name='TabletOptionRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_add', models.IntegerField(blank=True, null=True)),
                ('Tablet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tablet')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
            ],
        ),
        migrations.CreateModel(
            name='TabletOptionStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_add', models.IntegerField(blank=True, null=True)),
                ('Tablet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tablet')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
            ],
        ),
        migrations.RemoveField(
            model_name='tabletoption',
            name='Phone_id',
        ),
        migrations.RemoveField(
            model_name='tabletoption',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tabletoption',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='tabletoption',
            name='storage',
        ),
        migrations.DeleteModel(
            name='PhoneOption',
        ),
        migrations.DeleteModel(
            name='TabletOption',
        ),
    ]
