# Generated by Django 4.1.9 on 2023-06-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_product_delete_tablet_delete_watch'),
        ('home', '0009_phoneoptioncolor_phoneoptionram_phoneoptionstorage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOptionHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_add', models.IntegerField(blank=True, null=True)),
                ('Phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phone')),
                ('Storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phonestorage')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phoneram')),
            ],
        ),
        migrations.RemoveField(
            model_name='phoneoptionstorage',
            name='Phone_id',
        ),
        migrations.RemoveField(
            model_name='phoneoptionstorage',
            name='storage',
        ),
        migrations.AlterField(
            model_name='tabletoptionram',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tabletram'),
        ),
        migrations.AlterField(
            model_name='tabletoptionstorage',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tabletstorage'),
        ),
        migrations.DeleteModel(
            name='PhoneOptionRam',
        ),
        migrations.DeleteModel(
            name='PhoneOptionStorage',
        ),
    ]
