# Generated by Django 4.1.9 on 2023-06-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tabletoptionhard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabletoptionhard',
            old_name='storage',
            new_name='Storage',
        ),
    ]
